### ISSUE TITLE
About the lemma naming prefix `f`.

### ISSUE THREAD

**Issue by ejgallego** [Barbichu/finmap#2]
Almost all lemmas in `finmap` are named following `finset` but prefixed with a `f`. Thus, `setUP` becomes `fsetUP`, etc...

However, I'm not sure this is the best approach; why not use the same names? The user could use Coq namespaces to select between the two.

My motivation is that I have many proofs that go basically unchanged between `set` and `fset` but for the prefix. See for instance #1, the proof of `bigfcup_sup` is exactly the same than in `finset.v` but for the name [the same applies for all other lemmas in that issue].

**Comment by Barbichu** [comment]
finmap depends on finset in a non opaque way so one might have to use finset namespace at the same time as finmap namespace. That's also why the notations are different.

**Comment by ejgallego** [comment]
Umm, I thought they indeed could be shared; I was thinking of doing something like this:

https://github.com/ejgallego/finmap/tree/set-noinline

Is a bit hacky now but it could certainly work better with a bit of cooperation from finset.

What do you think?

**Comment by ejgallego** [comment]
Just another quick note, I did some experiments and indeed I don't understand why sharing notations is not possible; indeed it requires a bit of surgery on finset but other than that...

**Comment by Barbichu** [comment]
It's not a matter of impossibility but of readability for the user in the presence of both {fset K} and {set K}.

**Comment by ejgallego** [comment]
Closing this as not relevant anymore!
